# Generated by Django 4.1.4 on 2023-01-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='tweet',
        ),
    ]
