# Generated by Django 4.1.4 on 2023-01-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_remove_notification_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread_notifications',
            field=models.IntegerField(default=0),
        ),
    ]
