# Generated by Django 4.1.4 on 2022-12-31 22:26

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_profile_remove_following_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
    ]
