# Generated by Django 4.1.4 on 2023-01-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_profile_unread_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unread_notifications',
        ),
    ]
