# Generated by Django 4.1.4 on 2023-01-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
