# Generated by Django 4.1.4 on 2023-01-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_remove_tweet_likes_tweet_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retweet',
        ),
    ]
